# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'dca_test_data' so R CMD check does not flag undocumented data.
#' dca_test_data: example dataset for the meddecide module
#'
#' Example dataset distributed with the meddecide jamovi module for demonstration and testing.
#'
#' @format A data frame with 800 rows and 19 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{age}{integer variable}
#'   \item{sex}{character variable}
#'   \item{diabetes}{character variable}
#'   \item{hypertension}{character variable}
#'   \item{smoking}{character variable}
#'   \item{cholesterol}{integer variable}
#'   \item{troponin}{numeric variable}
#'   \item{creatinine}{numeric variable}
#'   \item{cardiac_event_numeric}{integer variable}
#'   \item{cardiac_event}{character variable}
#'   \item{true_risk}{numeric variable}
#'   \item{basic_model}{numeric variable}
#'   \item{enhanced_model}{numeric variable}
#'   \item{biomarker_model}{numeric variable}
#'   \item{miscalibrated_model}{numeric variable}
#'   \item{poor_model}{numeric variable}
#'   \item{risk_category}{character variable}
#'   \item{hospital}{character variable}
#' }
#' @keywords datasets internal
"dca_test_data"

