# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'bayesdca_test_data' so R CMD check does not flag undocumented data.
#' bayesdca_test_data: example dataset for the meddecide module
#'
#' Example dataset distributed with the meddecide jamovi module for demonstration and testing.
#'
#' @format A data frame with 500 rows and 4 variables:
#' \describe{
#'   \item{outcome}{character variable}
#'   \item{model_prediction}{numeric variable}
#'   \item{binary_test}{integer variable}
#'   \item{weak_test}{integer variable}
#' }
#' @keywords datasets internal
"bayesdca_test_data"

