# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'lymphoma_diagnostic_styles' so R CMD check does not flag undocumented data.
#' lymphoma_diagnostic_styles: example dataset for the meddecide module
#'
#' Example dataset distributed with the meddecide jamovi module for demonstration and testing.
#'
#' @format An object of class list of length 3.
#' @keywords datasets internal
"lymphoma_diagnostic_styles"

