# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'cardiac_data' so R CMD check does not flag undocumented data.
#' cardiac_data: example dataset for the meddecide module
#'
#' Example dataset distributed with the meddecide jamovi module for demonstration and testing.
#'
#' @format A data frame with 500 rows and 11 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{age}{numeric variable}
#'   \item{sex}{factor variable}
#'   \item{hs_troponin_0h}{numeric variable}
#'   \item{hs_troponin_3h}{numeric variable}
#'   \item{hs_troponin_6h}{numeric variable}
#'   \item{delta_troponin}{numeric variable}
#'   \item{diabetes}{factor variable}
#'   \item{hypertension}{factor variable}
#'   \item{smoking}{factor variable}
#'   \item{mi_status}{factor variable}
#' }
#' @keywords datasets internal
"cardiac_data"

