# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'breast_cancer_data' so R CMD check does not flag undocumented data.
#' breast_cancer_data: example dataset for the meddecide module
#'
#' Example dataset distributed with the meddecide jamovi module for demonstration and testing.
#'
#' @format A data frame with 2000 rows and 10 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{clinical_exam}{character variable}
#'   \item{mammography}{character variable}
#'   \item{ultrasound}{character variable}
#'   \item{mri}{character variable}
#'   \item{cancer_status}{character variable}
#'   \item{age}{integer variable}
#'   \item{family_history}{character variable}
#'   \item{brca_mutation}{character variable}
#'   \item{breast_density}{character variable}
#' }
#' @keywords datasets internal
"breast_cancer_data"

