# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'sepsis_data' so R CMD check does not flag undocumented data.
#' sepsis_data: example dataset for the meddecide module
#'
#' Example dataset distributed with the meddecide jamovi module for demonstration and testing.
#'
#' @format A data frame with 500 rows and 10 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{age}{numeric variable}
#'   \item{sex}{factor variable}
#'   \item{procalcitonin}{numeric variable}
#'   \item{crp}{numeric variable}
#'   \item{wbc}{numeric variable}
#'   \item{lactate}{numeric variable}
#'   \item{sofa_score}{integer variable}
#'   \item{admission_source}{factor variable}
#'   \item{sepsis_status}{factor variable}
#' }
#' @keywords datasets internal
"sepsis_data"

