# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'breast_data' so R CMD check does not flag undocumented data.
#' breast_data: example dataset for the meddecide module
#'
#' Example dataset distributed with the meddecide jamovi module for demonstration and testing.
#'
#' @format An object of class list of length 3.
#' @keywords datasets internal
"breast_data"

