# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'master_data' so R CMD check does not flag undocumented data.
#' master_data: example dataset for the meddecide module
#'
#' Example dataset distributed with the meddecide jamovi module for demonstration and testing.
#'
#' @format An object of class list of length 4.
#' @keywords datasets internal
"master_data"

