# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'comprehensive_dca_data' so R CMD check does not flag undocumented data.
#' comprehensive_dca_data: example dataset for the meddecide module
#'
#' Example dataset distributed with the meddecide jamovi module for demonstration and testing.
#'
#' @format A data frame with 600 rows and 14 variables:
#' \describe{
#'   \item{id}{integer variable}
#'   \item{age}{numeric variable}
#'   \item{gender}{character variable}
#'   \item{model_excellent}{numeric variable}
#'   \item{model_good}{numeric variable}
#'   \item{model_poor}{numeric variable}
#'   \item{model_miscalibrated}{numeric variable}
#'   \item{sensitive_test}{integer variable}
#'   \item{specific_test}{integer variable}
#'   \item{balanced_test}{integer variable}
#'   \item{biomarker_high_good}{numeric variable}
#'   \item{biomarker_low_good}{numeric variable}
#'   \item{outcome}{integer variable}
#'   \item{biomarker_high_prob}{numeric variable}
#' }
#' @keywords datasets internal
"comprehensive_dca_data"

