# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'cancer_data' so R CMD check does not flag undocumented data.
#' cancer_data: example dataset for the meddecide module
#'
#' Example dataset distributed with the meddecide jamovi module for demonstration and testing.
#'
#' @format A data frame with 500 rows and 11 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{age}{numeric variable}
#'   \item{age_group}{factor variable}
#'   \item{sex}{factor variable}
#'   \item{ca125}{numeric variable}
#'   \item{he4}{numeric variable}
#'   \item{cea}{numeric variable}
#'   \item{ca199}{numeric variable}
#'   \item{roma_score}{numeric variable}
#'   \item{cancer_status}{factor variable}
#'   \item{stage}{factor variable}
#' }
#' @keywords datasets internal
"cancer_data"

