# GENERATED by _updateModules.R -- do not edit. Auto-documents the bundled
# example dataset 'thyroid_data' so R CMD check does not flag undocumented data.
#' thyroid_data: example dataset for the meddecide module
#'
#' Example dataset distributed with the meddecide jamovi module for demonstration and testing.
#'
#' @format A data frame with 500 rows and 9 variables:
#' \describe{
#'   \item{patient_id}{integer variable}
#'   \item{age}{numeric variable}
#'   \item{sex}{factor variable}
#'   \item{tsh}{numeric variable}
#'   \item{ft4}{numeric variable}
#'   \item{ft3}{numeric variable}
#'   \item{anti_tpo}{numeric variable}
#'   \item{symptom_score}{integer variable}
#'   \item{thyroid_status}{factor variable}
#' }
#' @keywords datasets internal
"thyroid_data"

