# GENERATED by _updateModules tooling: @importFrom tags to satisfy R CMD check
# 'Namespaces in Imports field not imported from' NOTE for pkg::-used packages.
#' @importFrom DescTools CCC
#' @importFrom ggraph ggraph
#' @importFrom glmnet cv.glmnet
#' @importFrom graphics par
#' @importFrom grDevices colorRampPalette
#' @importFrom grid arrow
#' @importFrom igraph graph_from_data_frame
#' @importFrom irrCAC gwet.ac1.raw
#' @importFrom kappaSize PowerBinary
#' @importFrom knitr kable
#' @importFrom lme4 lmer
#' @importFrom lmerTest as_lmerModLmerTest
#' @importFrom Matrix nearPD
#' @importFrom poLCA poLCA
#' @importFrom psych cohen.kappa
#' @importFrom tibble rownames_to_column
#' @importFrom tools toTitleCase
#' @importFrom vcd Kappa
#' @importFrom withr local_seed
NULL

